version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
    container_name: docker-compose-web
    image: cyebukayire/docker-compose:employees

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    container_name: docker-compose-postgres


  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "peace@example.com"
  #     PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgres